import os
import uuid
import base64
from io import BytesIO

import matplotlib
matplotlib.use("Agg")  # headless rendering, no GUI backend needed
import matplotlib.pyplot as plt
import pandas as pd

from fastapi import FastAPI, Query, Request
from fastapi.staticfiles import StaticFiles

from db_connection import get_connection

# --------------------------------------------------------------------------
# APP SETUP
# --------------------------------------------------------------------------

REPORTS_DIR = "../reports/customer_reports"
os.makedirs(REPORTS_DIR, exist_ok=True)

app = FastAPI(
    title="Retail Analytics API",
    version="1.0.0",
    description="Retail Dashboard APIs — every endpoint also generates an "
                 "HTML report (table + chart) and returns its link as "
                 "`report_url` in the JSON response.",
)

# Serves everything saved into REPORTS_DIR at http://<host>/reports/<file>.html
app.mount("/reports", StaticFiles(directory=REPORTS_DIR), name="reports")


# --------------------------------------------------------------------------
# CHART + HTML REPORT HELPERS
# --------------------------------------------------------------------------

def df_to_base64_chart(df: pd.DataFrame, x_col: str, y_col: str,
                        title: str, kind: str = "bar") -> str | None:
    """Render a matplotlib chart for the dataframe and return it as a
    base64 PNG string (so the HTML report is a single self-contained file,
    no separate image files to manage)."""
    if df.empty or x_col not in df.columns or y_col not in df.columns:
        return None

    fig, ax = plt.subplots(figsize=(10, 5.5))
    plot_df = df.head(30)  # keep charts readable if a report has many rows

    if kind == "pie":
        ax.pie(plot_df[y_col], labels=plot_df[x_col].astype(str), autopct="%1.1f%%")
        ax.set_title(title)
    else:
        ax.bar(plot_df[x_col].astype(str), plot_df[y_col], color="#4C72B0")
        ax.set_title(title)
        ax.set_xlabel(x_col)
        ax.set_ylabel(y_col)
        plt.xticks(rotation=45, ha="right")

    plt.tight_layout()

    buf = BytesIO()
    fig.savefig(buf, format="png", dpi=110)
    plt.close(fig)
    buf.seek(0)
    return base64.b64encode(buf.read()).decode("utf-8")


def build_html_report(title: str, df: pd.DataFrame, chart_base64: str | None) -> str:
    chart_html = ""
    if chart_base64:
        chart_html = (
            f'<img src="data:image/png;base64,{chart_base64}" '
            f'alt="{title} chart">'
        )

    if df.empty:
        table_html = "<p class='empty'>No rows returned.</p>"
    else:
        table_html = df.to_html(index=False, classes="data-table", border=0)

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>{title}</title>
<style>
  body {{
    font-family: -apple-system, Segoe UI, Arial, sans-serif;
    margin: 40px auto; max-width: 1000px; background: #f5f6fa; color: #222;
  }}
  h1 {{ color: #2b2f42; border-bottom: 3px solid #4C72B0; padding-bottom: 10px; }}
  .meta {{ color: #666; font-size: 0.85rem; margin-bottom: 25px; }}
  img {{
    max-width: 100%; border: 1px solid #ddd; border-radius: 6px;
    padding: 10px; background: #fff; margin-bottom: 30px;
    box-shadow: 0 1px 4px rgba(0,0,0,0.08);
  }}
  table.data-table {{
    border-collapse: collapse; width: 100%; background: #fff;
    box-shadow: 0 1px 4px rgba(0,0,0,0.08);
  }}
  table.data-table th, table.data-table td {{
    border: 1px solid #e3e3e3; padding: 8px 12px; text-align: left; font-size: 0.9rem;
  }}
  table.data-table th {{ background: #4C72B0; color: #fff; }}
  table.data-table tr:nth-child(even) {{ background: #f8f9fb; }}
  .empty {{ color: #888; font-style: italic; }}
</style>
</head>
<body>
  <h1>{title}</h1>
  <div class="meta">{len(df)} row(s) &middot; generated by Retail Analytics API</div>
  {chart_html}
  {table_html}
</body>
</html>"""


def save_report(title: str, df: pd.DataFrame, x_col: str = None,
                 y_col: str = None, kind: str = "bar") -> str:
    """Builds the report, writes it to REPORTS_DIR, returns the relative
    URL path (e.g. /reports/customers_by_state_ab12cd34.html)."""
    chart_b64 = df_to_base64_chart(df, x_col, y_col, title, kind) if x_col and y_col else None
    html = build_html_report(title, df, chart_b64)

    safe_name = title.lower().replace(" ", "_")
    filename = f"{safe_name}_{uuid.uuid4().hex[:8]}.html"
    filepath = os.path.join(REPORTS_DIR, filename)

    with open(filepath, "w", encoding="utf-8") as f:
        f.write(html)

    return f"/reports/{filename}"


def execute_query(query: str, request: Request, report_title: str,
                   x_col: str = None, y_col: str = None, kind: str = "bar"):
    """Runs the SQL, returns JSON data, and always attaches report_url
    pointing at the freshly generated HTML report."""
    conn = get_connection()
    try:
        df = pd.read_sql(query, conn)
        report_path = save_report(report_title, df, x_col, y_col, kind)

        return {
            "count": len(df),
            "data": df.to_dict(orient="records"),
            "report_url": str(request.base_url).rstrip("/") + report_path,
        }
    finally:
        conn.close()


##########################################################################
# CUSTOMER REPORTS
##########################################################################

@app.get("/customers/total")
def total_customers(request: Request):
    query = "SELECT COUNT(*) AS TOTAL_CUSTOMERS FROM CUSTOMERS;"
    return execute_query(query, request, "Total Customers")


@app.get("/customers/by-state")
def customers_by_state(request: Request):
    query = """
    SELECT STATE, COUNT(*) CUSTOMER_COUNT
    FROM CUSTOMERS
    GROUP BY STATE
    ORDER BY CUSTOMER_COUNT DESC;
    """
    return execute_query(query, request, "Customers by State",
                          x_col="STATE", y_col="CUSTOMER_COUNT")


@app.get("/customers/top")
def top_customers(request: Request,
                   top_n: int = Query(10, ge=1, le=100, description="Top N Customers")):
    query = f"""
    SELECT
        C.CUSTOMER_ID, C.CUSTOMER_NAME, SUM(O.NET_AMOUNT) TOTAL_PURCHASE
    FROM CUSTOMERS C
    JOIN ORDERS O ON C.CUSTOMER_ID = O.CUSTOMER_ID
    GROUP BY C.CUSTOMER_ID, C.CUSTOMER_NAME
    ORDER BY TOTAL_PURCHASE DESC
    LIMIT {top_n};
    """
    return execute_query(query, request, f"Top {top_n} Customers",
                          x_col="CUSTOMER_NAME", y_col="TOTAL_PURCHASE")

@app.get("/customers/active-inactive")
def active_inactive_customers(request: Request):
    query = """
    SELECT
        CUSTOMER_STATUS,
        COUNT(*) AS CUSTOMER_COUNT
    FROM (
        SELECT
            C.CUSTOMER_ID,
            CASE
                WHEN MAX(O.ORDER_DATE) >= CURRENT_DATE - INTERVAL '90 days' THEN 'ACTIVE'
                ELSE 'INACTIVE'
            END AS CUSTOMER_STATUS
        FROM CUSTOMERS C
        LEFT JOIN ORDERS O
            ON C.CUSTOMER_ID = O.CUSTOMER_ID
        GROUP BY C.CUSTOMER_ID
    ) T
    GROUP BY CUSTOMER_STATUS;
    """
    return execute_query(query, request, "Active vs Inactive Customers",
                          x_col="CUSTOMER_STATUS", y_col="CUSTOMER_COUNT", kind="pie")

@app.get("/customers/repeat")
def repeat_customers(request: Request):
    query = """
    SELECT
        C.CUSTOMER_ID, C.CUSTOMER_NAME, COUNT(O.ORDER_ID) TOTAL_ORDERS
    FROM CUSTOMERS C
    JOIN ORDERS O ON C.CUSTOMER_ID = O.CUSTOMER_ID
    GROUP BY C.CUSTOMER_ID, C.CUSTOMER_NAME
    HAVING COUNT(O.ORDER_ID) > 1
    ORDER BY TOTAL_ORDERS DESC;
    """
    return execute_query(query, request, "Repeat Customers",
                          x_col="CUSTOMER_NAME", y_col="TOTAL_ORDERS")


@app.get("/customers/highest-spending")
def highest_spending_customer(request: Request):
    query = """
    SELECT
        C.CUSTOMER_ID, C.CUSTOMER_NAME, SUM(O.NET_AMOUNT) TOTAL_SPENT
    FROM CUSTOMERS C
    JOIN ORDERS O ON C.CUSTOMER_ID = O.CUSTOMER_ID
    GROUP BY C.CUSTOMER_ID, C.CUSTOMER_NAME
    ORDER BY TOTAL_SPENT DESC
    LIMIT 1;
    """
    return execute_query(query, request, "Highest Spending Customer",
                          x_col="CUSTOMER_NAME", y_col="TOTAL_SPENT")


##########################################################################
# INVENTORY REPORTS
##########################################################################

@app.get("/inventory/quantity-sold-by-product")
def quantity_sold(request: Request):
    query = """
    SELECT P.PRODUCT_NAME, SUM(OI.QUANTITY) TOTAL_SOLD
    FROM ORDER_ITEMS OI
    JOIN PRODUCTS P ON OI.PRODUCT_ID = P.PRODUCT_ID
    GROUP BY P.PRODUCT_NAME
    ORDER BY TOTAL_SOLD DESC;
    """
    return execute_query(query, request, "Quantity Sold by Product",
                          x_col="PRODUCT_NAME", y_col="TOTAL_SOLD")


@app.get("/inventory/category-wise-sales")
def category_sales(request: Request):
    query = """
    SELECT P.CATEGORY, SUM(OI.QUANTITY) TOTAL_SOLD
    FROM ORDER_ITEMS OI
    JOIN PRODUCTS P ON OI.PRODUCT_ID = P.PRODUCT_ID
    GROUP BY P.CATEGORY
    ORDER BY TOTAL_SOLD DESC;
    """
    return execute_query(query, request, "Category-wise Sales",
                          x_col="CATEGORY", y_col="TOTAL_SOLD", kind="pie")


@app.get("/inventory/top-products")
def top_products(request: Request,
                  top_n: int = Query(10, ge=1, le=100)):
    query = f"""
    SELECT P.PRODUCT_NAME, SUM(OI.QUANTITY) TOTAL_SOLD
    FROM ORDER_ITEMS OI
    JOIN PRODUCTS P ON OI.PRODUCT_ID = P.PRODUCT_ID
    GROUP BY P.PRODUCT_NAME
    ORDER BY TOTAL_SOLD DESC
    LIMIT {top_n};
    """
    return execute_query(query, request, f"Top {top_n} Products",
                          x_col="PRODUCT_NAME", y_col="TOTAL_SOLD")



@app.get("/sales/total-sales")
def total_sales(request: Request):
    query = "SELECT SUM(NET_AMOUNT) TOTAL_SALES FROM ORDERS;"
    return execute_query(query, request, "Total Sales")


@app.get("/sales/by-payment-mode")
def payment_mode_sales(request: Request):
    query = """
    SELECT PAYMENT_MODE, SUM(NET_AMOUNT) TOTAL_SALES
    FROM ORDERS
    GROUP BY PAYMENT_MODE
    ORDER BY TOTAL_SALES DESC;
    """
    return execute_query(query, request, "Sales by Payment Mode",
                          x_col="PAYMENT_MODE", y_col="TOTAL_SALES", kind="pie")


@app.get("/sales/top-orders")
def top_orders(request: Request,
               top_n: int = Query(10, ge=1, le=100)):
    query = f"""
    SELECT ORDER_ID, CUSTOMER_ID, NET_AMOUNT
    FROM ORDERS
    ORDER BY NET_AMOUNT DESC
    LIMIT {top_n};
    """
    return execute_query(query, request, f"Top {top_n} Orders",
                          x_col="ORDER_ID", y_col="NET_AMOUNT")


##########################################################################
# STORE REPORTS
##########################################################################

@app.get("/stores/total")
def total_stores(request: Request):
    query = "SELECT COUNT(*) TOTAL_STORES FROM STORES;"
    return execute_query(query, request, "Total Stores")


@app.get("/stores/by-state")
def stores_by_state(request: Request):
    query = """
    SELECT STATE, COUNT(*) TOTAL_STORES
    FROM STORES
    GROUP BY STATE
    ORDER BY TOTAL_STORES DESC;
    """
    return execute_query(query, request, "Stores by State",
                          x_col="STATE", y_col="TOTAL_STORES")


@app.get("/stores/top")
def top_stores(request: Request,
               top_n: int = Query(10, ge=1, le=100)):
    query = f"""
    SELECT S.STORE_NAME, SUM(O.NET_AMOUNT) TOTAL_SALES
    FROM STORES S
    JOIN ORDERS O ON S.STORE_ID = O.STORE_ID
    GROUP BY S.STORE_NAME
    ORDER BY TOTAL_SALES DESC
    LIMIT {top_n};
    """
    return execute_query(query, request, f"Top {top_n} Stores",
                          x_col="STORE_NAME", y_col="TOTAL_SALES")